services:
  - type: web
    name: unstable-unicorns-online
    env: node
    plan: free
    buildCommand: npm install --include=dev --legacy-peer-deps && npm install typescript@^4.9.5 --legacy-peer-deps && npx tsc src/server.ts --outDir server_build --skipLibCheck --esModuleInterop true --target es2019 --module commonjs
    startCommand: npm run serve
    envVars:
      - key: NODE_ENV
        value: production
      - key: CI
        value: false
      - key: NODE_OPTIONS
        value: --max_old_space_size=400
      - key: GENERATE_SOURCEMAP
        value: "false"
